### ISSUE TITLE
Sorting does not appear to work

### ISSUE THREAD

**Issue by pkbullock** [pnp/m365-sample-gallery#10]
When sorting from oldest to newest and vise versa, does not appear to change the results.

**A-Z**

![image](https://user-images.githubusercontent.com/8781041/117783070-1d0a6580-b23a-11eb-871f-3bb3a2bcce37.png)

**Z-A**

![image](https://user-images.githubusercontent.com/8781041/117783121-285d9100-b23a-11eb-90c3-1b94d122c3b2.png)

**Comment by VesaJuvonen** [comment]
@v-aaronbode  - reopening as as missing any conclusions if the issue is fixed or when it has been released. Let's be a bit more clear on the communications, so that both teams knows what is happening and that the work done for testing is properly appreciated... and acknowledged and fixes properly communicated.

When we fix something - please let us know if things were fixed, skipped and when it's available in the web site. Just typical open-source communication model on being respectful on the people spending time here.

**Comment by v-aaronbode** [comment]
This issue has now been resolved and is working on the prod environment. Thanks, @pkbullock!
