### ISSUE TITLE
Test page

### ISSUE THREAD

**Issue by pkbullock** [pnp/m365-sample-gallery#11]
Few issues here:

- Link sections feel like test content
- YouTube and images do not work

![image](https://user-images.githubusercontent.com/8781041/117784107-1af4d680-b23b-11eb-9a2a-4497412b8555.png)

**Comment by VesaJuvonen** [comment]
@v-aaronbode  - reopening as as missing any conclusions if the issue is fixed or when it has been released. Let's be a bit more clear on the communications, so that both teams knows what is happening and that the work done for testing is properly appreciated... and acknowledged and fixes properly communicated.

When we fix something - please let us know if things were fixed, skipped and when it's available in the web site. Just typical open-source communication model on being respectful on the people spending time here.

**Comment by v-aaronbode** [comment]
Thanks, @pkbullock! This was a test sample that was removed from the API. It is not live in the prod environment. Thanks!
