### ISSUE TITLE
Page Result Count does not reflect the number of items

### ISSUE THREAD

**Issue by pkbullock** [pnp/m365-sample-gallery#15]
Hi

Just noticed that when searching for Power Apps for example, I have 58 results. But counting the cards, only 20 shown per page with only 2 pages so only showing 40 results.

![image](https://user-images.githubusercontent.com/8781041/117787426-5644d480-b23e-11eb-85e9-a3328b46851c.png)
***
![image](https://user-images.githubusercontent.com/8781041/117787456-5ba21f00-b23e-11eb-862b-d4194e8c23b3.png)

**Comment by VesaJuvonen** [comment]
@v-aaronbode  - reopening as as missing any conclusions if the issue is fixed or when it has been released. Let's be a bit more clear on the communications, so that both teams knows what is happening and that the work done for testing is properly appreciated... and acknowledged and fixes properly communicated.

When we fix something - please let us know if things were fixed, skipped and when it's available in the web site. Just typical open-source communication model on being respectful on the people spending time here.

**Comment by v-aaronbode** [comment]
This issue has now been resolved and is working on the prod environment. Thanks, @pkbullock!
