### ISSUE TITLE
Load the sample gallery error on page 8

### ISSUE THREAD

**Issue by pkbullock** [pnp/m365-sample-gallery#25]
URL used: https://adoption-dev.azurewebsites.net/sample-solution-gallery?sortby=title-false&keyword=&product=All%20Products&category=All%20Categories&action=ajax_plugin_call_sample_solution_gallery&page=8

To repo, simply open the gallery, click at the bottom page 8 - BOOM.

![image](https://user-images.githubusercontent.com/8781041/118631205-2a3dcc00-b7c7-11eb-87a7-1c5c536243cd.png)

**Comment by pkbullock** [comment]
Other pages open - im suspecting its a sample with some duff data thats blowing up the previewer.

**Comment by VesaJuvonen** [comment]
@v-aaronbode  - reopening as as missing any conclusions if the issue is fixed or when it has been released. Let's be a bit more clear on the communications, so that both teams knows what is happening and that the work done for testing is properly appreciated... and acknowledged and fixes properly communicated.

When we fix something - please let us know if things were fixed, skipped and when it's available in the web site. Just typical open-source communication model on being respectful on the people spending time here.

**Comment by v-aaronbode** [comment]
This issue has now been resolved and is working on the prod environment. Thanks!
