### ISSUE TITLE
Mobile View - Number of Pages

### ISSUE THREAD

**Issue by PopWarner** [pnp/m365-sample-gallery#26]
If the number of pages for the collection of samples is more than can fit in the normal width for the screen, it will go off-screen and cause odd horizontal scrolling.

![Sample-Gallery-Mobile-iPhoneXS-PageNumbers](https://user-images.githubusercontent.com/10676147/118888399-73b61600-b8b0-11eb-9464-2ff91b9f5399.PNG)

**Comment by VesaJuvonen** [comment]
@v-aaronbode  - reopening as as missing any conclusions if the issue is fixed or when it has been released. Let's be a bit more clear on the communications, so that both teams knows what is happening and that the work done for testing is properly appreciated... and acknowledged and fixes properly communicated.

When we fix something - please let us know if things were fixed, skipped and when it's available in the web site. Just typical open-source communication model on being respectful on the people spending time here.

**Comment by v-aaronbode** [comment]
This pagination issue has been resolved and is published to the prod environment.

<img width="496" alt="Screen Shot 2021-06-08 at 11 18 52 AM" src="https://user-images.githubusercontent.com/84800044/121259074-5dfe9580-c84b-11eb-83c4-98c0b64b536a.png">
